/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telasGraficas;

import Modelos.Calculos;
import Modelos.Valores;
import javax.swing.JOptionPane;

/**
 *
 * @author Ezeks
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        v1 = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        radioSubtrair = new javax.swing.JRadioButton();
        radioSoma = new javax.swing.JRadioButton();
        radioDividir = new javax.swing.JRadioButton();
        radioMultiplicar = new javax.swing.JRadioButton();
        radioExpoenteRaiz = new javax.swing.JRadioButton();
        calcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Valor 2:");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Mini Calculadora");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Valor 1:");

        radioSubtrair.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        radioSubtrair.setText("Subtrair");

        radioSoma.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        radioSoma.setText("Somar");
        radioSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSomaActionPerformed(evt);
            }
        });

        radioDividir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        radioDividir.setText("Dividir");

        radioMultiplicar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        radioMultiplicar.setText("Multiplicar");

        radioExpoenteRaiz.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        radioExpoenteRaiz.setText("Expoente/Raiz");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(radioSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioExpoenteRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(radioSoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioSubtrair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioMultiplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioDividir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioExpoenteRaiz)
                .addGap(18, 18, 18)
                .addComponent(calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSomaActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:

        if (radioSoma.isSelected()) {
            if (v1.getText().equals("") | v2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Um dos campos estão vazios! Verifique", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String valorn1 = v1.getText();
            String valorn2 = v2.getText();

            double val1 = Double.parseDouble(valorn1);
            double val2 = Double.parseDouble(valorn2);
            Valores v = new Valores();
            v.setValor1(val1);
            v.setValor2(val2);
            Calculos calc = new Calculos();
            double r1 = calc.soma(v);
            String r2 = String.valueOf(r1);
            resultado.setText(r2);
        }
        if (radioSubtrair.isSelected()) {
            if (v1.getText().equals("") | v2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Um dos campos estão vazios! Verifique", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String valorn1 = v1.getText();
            String valorn2 = v2.getText();

            double val1 = Double.parseDouble(valorn1);
            double val2 = Double.parseDouble(valorn2);
            Valores v = new Valores();
            v.setValor1(val1);
            v.setValor2(val2);
            Calculos calc = new Calculos();
            double r1 = calc.subtracao(v);
            String r2 = String.valueOf(r1);
            resultado.setText(r2);
        }

        if (radioMultiplicar.isSelected()) {
            if (v1.getText().equals("") | v2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Um dos campos estão vazios! Verifique", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String valorn1 = v1.getText();
            String valorn2 = v2.getText();

            double val1 = Double.parseDouble(valorn1);
            double val2 = Double.parseDouble(valorn2);
            Valores v = new Valores();
            v.setValor1(val1);
            v.setValor2(val2);
            Calculos calc = new Calculos();
            double r1 = calc.multiplicacao(v);
            String r2 = String.valueOf(r1);
            resultado.setText(r2);

        }

        if (radioDividir.isSelected()) {
            if (v1.getText().equals("") | v2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Um dos campos estão vazios! Verifique", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String valorn1 = v1.getText();
            String valorn2 = v2.getText();

            double val1 = Double.parseDouble(valorn1);
            double val2 = Double.parseDouble(valorn2);
            Valores v = new Valores();
            v.setValor1(val1);
            v.setValor2(val2);
            Calculos calc = new Calculos();

            try {
                double r1 = calc.divisao(v);
                String r2 = String.valueOf(r1);
                resultado.setText(r2);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao realizar divisão, não é possível dividir por zero ou negativo", "Warning", JOptionPane.WARNING_MESSAGE);
            }

        }

        if (radioExpoenteRaiz.isSelected()) {
            if (v2.getText().equals("")) {
                
                String valorn1 = v1.getText();
                double val1 = Double.parseDouble(valorn1);
                Valores vc = new Valores();
                vc.setValor1(val1);
                Calculos calc = new Calculos();
                double r1 = calc.raiz(vc);
                String r2 = String.valueOf(r1);
                resultado.setText(r2);
                //
            }
            String valorn1 = v1.getText();
            String valorn2 = v2.getText();

            double val1 = Double.parseDouble(valorn1);
            double val2 = Double.parseDouble(valorn2);
            Valores v = new Valores();
            v.setValor1(val1);
            v.setValor2(val2);
            Calculos calc = new Calculos();
            double r1 = calc.expoente(v);
            String r2 = String.valueOf(r1);
            resultado.setText(r2);

        }


    }//GEN-LAST:event_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton radioDividir;
    private javax.swing.JRadioButton radioExpoenteRaiz;
    private javax.swing.JRadioButton radioMultiplicar;
    private javax.swing.JRadioButton radioSoma;
    private javax.swing.JRadioButton radioSubtrair;
    private javax.swing.JTextField resultado;
    private javax.swing.JTextField v1;
    private javax.swing.JTextField v2;
    // End of variables declaration//GEN-END:variables
}
